name: Deploy Backend (EC2)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo ">>> Entrando al directorio del proyecto"
            cd ~/AYD2_V1S2025_PROYECTO_G1/backend

            echo ">>> Reseteando y actualizando código"
            git fetch origin main
            git reset --hard origin/main

            echo ">>> Construyendo nueva imagen Docker"
            docker build -t api-ayd2 .

            echo ">>> Reiniciando servicio Docker"
            sudo systemctl restart api-docker.service

            echo "✅ Despliegue completado"