on: 
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.8'  

      - name: Install dependencies
        run: |
          pip install pytest
          pip install flask
          pip install /home/runner/work/AYD2_V1S2025_PROYECTO_G1/AYD2_V1S2025_PROYECTO_G1/backend/requirements.txt

      - name: Run tests
        run: |
          cd /home/runner/work/AYD2_V1S2025_PROYECTO_G1/AYD2_V1S2025_PROYECTO_G1/backend/  
          pytest -v  