name: Deploy Backend (EC2)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo ">>> Cambiando al directorio del proyecto"
            cd /home/ubuntu/AYD2_V1S2025_PROYECTO_G1

            echo ">>> Limpiando y actualizando el repo"
            git reset --hard
            git pull origin main

            echo ">>> Navegando a la carpeta del backend"
            cd backend

            echo ">>> Reconstruyendo la imagen Docker"
            docker build -t api-ayd2 .

            echo ">>> Reiniciando el servicio del contenedor Docker"
            sudo systemctl daemon-reexec
            sudo systemctl restart api-docker.service

            echo ">>> Despliegue completado exitosamente"