name: Deploy Test 
on:
  push:
    branches:
      - main
    paths:
      - 'backend**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            pytest -v
