name: Deploy RDS

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy RDS and Load DDL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/rds

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform apply -auto-approve \
            -var="db_user=${{ secrets.TF_DB_USER }}" \
            -var="db_password=${{ secrets.TF_DB_PASSWORD }}"
        working-directory: ./terraform/rds

      # - name: Obtener endpoint RDS y guardarlo en archivo
      #   run: terraform output -raw rds_endpoint > rds_endpoint.txt
      #   working-directory: ./terraform/rds

      # - name: Mostrar contenido del archivo
      #   run: cat ./terraform/rds_endpoint.txt
