name: Deploy Backend (EC2)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy backend on EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo ">>> Accediendo al proyecto"
            cd /home/ubuntu/AYD2_V1S2025_PROYECTO_G1
            echo ">>> Reseteando y haciendo pull del repositorio"
            git reset --hard
            git pull origin main

            echo ">>> Construyendo imagen Docker actualizada"
            cd backend
            docker build -t api-ayd2 .

            echo ">>> Reiniciando servicio Docker"
            sudo systemctl restart api-docker.service

            echo "Despliegue completado exitosamente"