name: Deploy Backend (EC2)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd AYD2_V1S2025_PROYECTO_G1/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          cd AYD2_V1S2025_PROYECTO_G1/backend
          pytest -v

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/AYD2_V1S2025_PROYECTO_G1/backend
            git reset --hard
            git pull origin main
            docker build -t api-ayd2 .
            sudo systemctl restart api-docker.service
